server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: 86338633
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HZ
#        namespace: fab3e84b-6137-4655-9aef-b79cf4b6d773
        ephemeral: false
mybatis:
  type-aliases-package: com.stone.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.stone: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
ribbon:
  eager-load:
    enabled: true
    clients:
     - userservice
#feign:
#  client:
#    config:
#      default:
#        loggerLevel: FULL