server:
  port: 8082
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_demo?useSSL=false
    username: root
    password: 86338633
  cloud:
    nacos:
      server-addr: localhost:8848
mybatis-plus:
  global-config:
    db-config:
      insert-strategy: not_null
      update-strategy: not_null
      id-type: auto
logging:
  level:
    org.springframework.cloud.alibaba.seata.web: debug
    com.stone: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS