logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: stone
    password: 1234
    virtual-host: /
    listener:
      simple:
        prefetch: 1