server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?useSSL=false
    username: root
    password: 86338633
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.stone: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.stone.hotel.pojo