server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos的地址
    gateway:
      routes:
        - id: user-service # 路由标识 必须唯一
          uri: lb://userservice # 路由的目标地址
          predicates: # 路由断言 判断请求是否符合规则
            - Path=/user/**
#          filters:
#            - AddRequestHeader=Slogan, Stone is freaking awesome!
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
      default-filters:
        - AddRequestHeader=Slogan, Stone is freaking awesome!
        - AddRequestHeader=origin, gateway
